---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]  #if any chnages happend in main branch it will trigger 
jobs:
  build-push-gcr:
    name: Build and Push to GCP #arbitary name 
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lesson-087
      PROJECT_ID: cicd-396510 # Here is the project id which need to change 
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@v3    #gclode action 
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image   #Docker image building step
      run: docker build -t $IMAGE_NAME:latest .

    # - name: Automatic Tagging of Releases
    #   id: increment-git-tag
    #   run: |
    #     bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client  #Authentication step while pussing the images into gcr
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)  #lets push the docker image to gcr
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    # - name: Push Docker Image to Artifact Registry
    #   env:
    #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
    #   run: |-
    #     docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
    #     docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
    #     docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
    #     docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
